library(dplyr)
library(stringr)

neighborhoods_clusters = read.csv("neighborhoods_clustered.csv")
neighborhoods_clusters

apartments = read.csv("apartments.csv")
apartments

merged = merge(x=neighborhoods_clusters, y=apartments)
write.csv(merged, file = "apartments_clustered.csv")

mergedWithNumPrice <- mutate(merged, NumPrice = str_replace(Price, '\\$', ''))
mergedWithNumPrice <- mutate(mergedWithNumPrice, NumPrice = str_replace(NumPrice, ' ', ''))
mergedWithNumPrice <- mutate(mergedWithNumPrice, NumPrice = str_replace(NumPrice, ',', ''))
mergedWithNumPrice <- mutate(mergedWithNumPrice, NumPrice = as.numeric(NumPrice))

mergedCluster1 = filter(mergedWithNumPrice, Cluster == 1)
mergedCluster2 = filter(mergedWithNumPrice, Cluster == 2)
mergedCluster3 = filter(mergedWithNumPrice, Cluster == 3)
mergedCluster4 = filter(mergedWithNumPrice, Cluster == 4)
mergedCluster5 = filter(mergedWithNumPrice, Cluster == 5)
mergedCluster6 = filter(mergedWithNumPrice, Cluster == 6)
mergedCluster7 = filter(mergedWithNumPrice, Cluster == 7)
mergedCluster8 = filter(mergedWithNumPrice, Cluster == 8)
mergedCluster9 = filter(mergedWithNumPrice, Cluster == 9)
mergedCluster10 = filter(mergedWithNumPrice, Cluster == 10)
mergedCluster11 = filter(mergedWithNumPrice, Cluster == 11)
mergedCluster12 = filter(mergedWithNumPrice, Cluster == 12)
mergedCluster13 = filter(mergedWithNumPrice, Cluster == 13)
mergedCluster14 = filter(mergedWithNumPrice, Cluster == 14)
mergedCluster15 = filter(mergedWithNumPrice, Cluster == 15)
mergedCluster16 = filter(mergedWithNumPrice, Cluster == 16)

summarize(mergedCluster1, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster2, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster3, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster4, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster5, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster6, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster7, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster8, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster9, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster10, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster11, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster12, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster13, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster14, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster15, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
summarize(mergedCluster16, mean=mean(NumPrice), median=median(NumPrice), min=min(NumPrice), max=max(NumPrice))
